# Generated by Django 4.2.6 on 2023-11-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='timestamp',
            new_name='date_created',
        ),
    ]
