# Generated by Django 4.2.6 on 2023-11-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_password_user_id_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_password',
            new_name='password',
        ),
    ]
