# Generated by Django 4.2.6 on 2023-11-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_password_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_confirmation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
