# Generated by Django 4.2.6 on 2023-11-10 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_password_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_confirmation',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='2222\t31s2s31')]),
        ),
    ]
