# Generated by Django 4.2.6 on 2023-11-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_password_user_password1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', help_text='Obligatory field. No more than 150 characters.                                              Only letters, numbers and symbols @/./+/-/_.', max_length=150, unique=True),
        ),
    ]
