# Generated by Django 4.2.6 on 2023-11-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_rename_users_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
