# Generated by Django 4.2.8 on 2023-12-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_label_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Метка', 'verbose_name_plural': 'Метки'},
        ),
    ]
