# Generated by Django 4.2.6 on 2023-12-04 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, through='tasks.TaskRelationLabel', to='labels.label'),
        ),
        migrations.AlterField(
            model_name='taskrelationlabel',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='labels.label'),
        ),
    ]
