# Generated by Django 4.2.6 on 2023-11-23 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 14, 47, 0, 370771, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
