# Generated by Django 4.2.6 on 2023-12-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0008_alter_status_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='date_joined',
            new_name='created_at',
        ),
    ]
